project:
  type: manuscript
  execute-dir: project

manuscript: 
  article: index.qmd

format:
  html: 
    theme: litera
    mainfont: serif
    fontsize: 1em
    linestretch: 1.6
    css: styles.css
    title-block-banner: "#f4f4f4"
  docx: 
    reference-doc: reference.docx 
    toc: TRUE

execute: 
  freeze: auto

