---
title: Clinical Psychology Portfolio
author:
  - name: Estelle Higgins
    affiliations:
      - Department of Psychology, University of Wisconsin-Madison
date: last-modified
number-sections: true 
number-depth: 3
editor_options: 
  chunk_output_type: console
---

## Background

### Personal Statement

### Curriculum Vitae

-   [Current CV](https://github.com/higgins5/Portfolio/blob/main/documents/EstelleHiggins_CV_062025.pdf)

### Transcript

-   [Unofficial Transcript](https://github.com/higgins5/Portfolio/blob/main/documents/Higgins_UWTranscript.pdf)

## Research Experiences

### Research Statement

statement:

### First-Author Publications

1.  **Higgins, E. T.**, Busse, W. W., Esnault, S., Christian, B. T., Klaus, D. R., Bach, J. C., Frye, C. J., Rosenkranz, M. A. (2025). Fueling the fire in the lung-brain axis: the salience network connects allergen-provoked TH17 responses to psychological stress in asthma. *Brain, Behavior, & Immunity, 128,* 276-288. https://doi.org/10.1016/j.bbi.2025.04.004

    **Abstract**: Asthma, a highly prevalent chronic inflammatory disease of the airways, results in an average of 10 deaths per day in the U.S., and psychological stress hinders its effective management. Threat-sensitive neurocircuitry, active during psychological stress, may intensify airway inflammatory responses and contribute to poor clinical outcomes. However, the neural mechanisms and descending pathways connecting acute stress and inflammatory responses to allergen exposure remain poorly understood. We hypothesized that stress-induced engagement of the salience network would prime Th17 immune pathways and potentiate airway inflammation. We measured brain glucose metabolism during the Trier Social Stress Test (TSST) and a non-stressful control task using \[18F\]fluorodeoxyglucose positron emission tomography (PET) in 28 adults (18F) with asthma. Salivary cortisol was collected to quantify physiological stress responses. Before and after airway provocation with a whole-lung allergen challenge (WL-AG), airway inflammation was assessed using fraction of exhaled nitric oxide (FeNO), sputum % eosinophils, and expression of Th17-related cytokine mRNA in the airway. As expected, the WL-AG increased all inflammatory biomarkers. Acute stress significantly increased salivary cortisol (t(27.3) = -27.3, p \< 0.01), but did not significantly affect airway inflammation overall. Instead, more robust cortisol responses to stress predicted increased glucose metabolism in the amygdala, insula, and dorsal anterior cingulate cortex, key nodes in the salience network, as well as increased IL-23A mRNA expression (t(22.1) = 2.38, p = 0.026) and FeNO (t(21.5) = 2.17, p = 0.041). Moreover, differential increases in amygdala and dACC glucose metabolism predicted differential increases IL-23A mRNA expression following WL-AG. In addition, compared to low chronic stress, high chronic stress was associated with enhanced IL-17A mRNA expression in response to acute stress and WL-AG. Individual differences in salience network and cortisol responses to acute stress predict enhanced allergen challenge-provoked Th17-related responses, advancing our understanding of the efferent arm of the lung-brain axis in asthma. This work underscores the importance of translational research for the development of novel interventions that target stress-sensitive brain and immune pathways.

-   Relative contributions:
    -   Conceptualization - 0%\
    -   Design - 0%\
    -   Analyses - 100%\
    -   Writing - 70%\
-   Full-text PDF available [here](https://github.com/higgins5/Portfolio/blob/main/documents/manuscripts/Higgins_etall2025_BBI.pdf)

2.  **Higgins, E. T.**, Davidson, R. J., Busse, W. W., Klaus, D. R., Bednarek, G. T., Goldman, R. I., Sachs, J., & Rosenkranz, M. A. (2022). Clinically relevant effects of Mindfulness-Based Stress Reduction in individuals with asthma. *Brain, Behavior, & Immunity - Health, 25,* 100509. https://doi.org/10.1016/j.bbih.2022.100509

    **Abstract:** Psychological distress and comorbid psychopathology contribute to exacerbation risk in patients with asthma. Thus, interventions designed to reduce stress and improve emotion regulation, such as Mindfulness-Based Stress Reduction (MBSR), may augment standard care. Few studies have addressed this question and a paucity of data exists to determine the ability of MBSR to impact clinical outcomes in asthma. This randomized controlled trial investigated effects of MBSR training on asthma control and airway inflammation, in relation to psychological symptoms, in adults with asthma. Participants were randomized to an 8-week MBSR training (n = 35) or wait-list control group (n = 34). Clinically relevant asthma assessments, including Asthma Control Questionnaire and inflammatory biomarkers, were collected at baseline and six approximately-monthly follow-ups. Self-reported mindfulness, distress, depression, and anxiety symptoms were assessed at baseline, post-intervention, and study completion. Chronic stress level was determined at baseline only. Asthma control improved significantly in individuals randomized to MBSR, relative to wait-list controls (p = .01; effect size d = 0.76), which was maintained at 4mo post-intervention. 32% of MBSR participants achieved a clinically significant improvement, based on the ACQ6 Minimally Important Difference, relative to 12% of wait-list participants. Moreover, MBSR-related improvement in asthma control was associated with a reduction in distress (p = .043) and the intervention was most efficacious for those with the highest baseline depressive symptoms (p = .023). Importantly, MBSR also reduced levels of exhaled nitric oxide, a biomarker of airway inflammation, relative to wait-list controls (p \< .05). Supporting and extending extant evidence of mind-body relationships in asthma and the benefits of stress reduction for these patients, this is, to the best of our knowledge, the first RCT to demonstrate that training in MBSR improves clinically relevant asthma outcomes. MBSR may thus be a valuable addition to optimal asthma management, particularly for those with comorbid psychopathology.

-   Relative contributions:
    -   Conceptualization - 0%\
    -   Design - 0%\
    -   Analyses - 100%\
    -   Writing - 60%\
-   Full-text PDF available [here](https://github.com/higgins5/Portfolio/blob/main/documents/manuscripts/Higgins_etal2022_BBI-H.pdf)

### Coauthor Publications

1.  Abercrombie, H., Barnes, A., Nord, E., Finley, A., **Higgins, E.T.**, Grupe, D., Rosenkranz, M. A., Davidson, R. J., Schaefer, S. M. (2023). Inverse association between stress induced cortisol elevations and negative emotional reactivity to stress in humans. *Stress, 26*(1), 2174780. https://doi.org/10.1080/10253890.2023.2174780

    **Abstract:** Greater cortisol reactivity to stress is often assumed to lead to heightened negative affective reactivity to stress. Conversely, a growing body of evidence demonstrates mood-protective effects of cortisol elevations in the context of acute stress. We administered a laboratory-based stressor, the Trier Social Stress Test (TSST), and measured cortisol and emotional reactivity in 68 adults (48 women) between the ages of 25 and 65. In accordance with our pre-registered hypothesis (https://osf.io/t8r3w) and prior research, negative affective reactivity was inversely related to cortisol reactivity assessed immediately after the stressor. We found that greater cortisol response to acute stress is associated with smaller increases in negative affect, consistent with mood-protective effects of cortisol elevations in response to acute stress.

-   Relative contributions:
    -   Conceptualization - 0%\
    -   Design - 0%\
    -   Analyses - 15%\
    -   Writing - 5%\
-   Full-text PDF available [here](https://github.com/higgins5/Portfolio/blob/main/documents/manuscripts/Abercrombie_etal2024-Stress.pdf)

### In-Progress Manuscripts (Meaningful Empirical Study)

1.  **Higgins, E. T.**, Busse, W. W., Klaus, D., Grupe, D. W., Davidson, R. J., & Rosenkranz, M. A. (in progress). Mindfulness-Based Stress Reduction alters neural responses associated with asthma outcomes.

    **Abstract**: Psychological distress negatively impacts asthma control, airway inflammation, and treatment efficacy, suggesting crosstalk between the brain and disease symptoms in asthma. Mindfulness-Based Stress Reduction (MBSR), which promotes non-judgmental attention to internal and external cues, can benefit psychological and physical symptoms in chronic inflammatory diseases, including increasing asthma control. Understanding the neural mechanisms underlying these benefits in asthma could help identify phenotypes and personalize interventions for asthma. Adults with asthma were randomized to an 8-week MBSR training (n = 35) or wait-list control group (n = 34). Clinically relevant asthma-related and psychological outcomes were collected, and task-based functional magnetic resonance scans were acquired during the presentation of emotionally-salient cues at baseline, post-intervention, and 6mo follow-up. Mindfulness training decreased lateral prefrontal/orbitofrontal cortex responses to emotionally-salient cues relative to wait-list controls, which was associated with increased self-reported mindfulness. Additionally, reductions in psychological distress and inflammation were associated with decreased neural reactivity in the insula/frontal-opercular cortex (IFOC), dorsal anterior cingulate cortex, and amygdala for all participants immediately post-intervention. At 6-month follow-up, though some relationships persisted, MBSR-related improvements in asthma control, severity, and overall distress were associated with increased neural reactivity in medial prefrontal and IFOC regions. In the first study to investigate MBSR’s effects on neural responses to aversive cues and disease outcomes in adults with asthma, decreased neural reactivity associated with increased mindfulness suggests a reduced need for effortful cognitive-affective regulation immediately post-intervention. For all participants, reduced neural reactivity was associated with reduced distress and inflammation, supporting the hypothesis that cognitive-affective processing is integrated with peripheral inflammation in asthma. At the 6mo follow-up, additional associations between improved symptoms and increased neural reactivity point to increased effortful regulation. Overall, MBSR alters the reactivity and regulation of neural responses to emotionally-salient cues, which predicts symptom improvements. Results here shed light on neural mechanisms that may underlie clinical benefits of MBSR for asthma, and highlight the importance of addressing mind-body relationships in asthma management.

2.  Haeffer, C. E.\*, **Higgins, E. T.**\*, Laubacher, C. M., Gresham, L. K., Barnes, A. L., Skinner, S. E., Nord, E., Abercrombie, H. C., Rosenkranz, M. A., Davidson, R. J., Slavich, G. M., Schaefer, S. M. (in progress). Associations among lifetime stressor severity, cortisol responses to acute stress, and amygdala and hippocampal volumes.\
\**Co-first-authors*

    **Abstract**: Severe stress is linked to structural changes in the amygdala and hippocampus, limbic regions with roles in regulating hypothalamic-pituitary-adrenal (HPA) responses to acute stress. Yet, how these amygdalar and hippocampal structural changes may in turn influence subsequent acute biological stress responses remains unclear. 249 individuals (aged 25-65) completed the Stress and Adversity Inventory (STRAIN), underwent structural magnetic resonance imaging (MRI), and provided salivary cortisol samples during their reactivity to and recovery from a psychosocial stress paradigm, the Trier Social Stress Test (TSST). Linear regression and piecewise mixed-effects models were used to examine relations between lifetime stressor severity, amygdalar and hippocampal volumes, and cortisol response patterns. Lifetime stressor severity from the STRAIN was associated with both smaller amygdala and hippocampal volumes, adjusted for intracranial volume (ICV) and cohort (data collected before vs. after Covid-19 pandemic shutdowns), but only associations with the hippocampus remained at trend when age, sex at birth, and race were included in the model. Flatter cortisol reactivity and recovery patterns and lower peak cortisol were associated with smaller amygdala and hippocampal volumes and greater lifetime stressor severity. These results confirm the expected intersections between stress exposure, amygdalar and hippocampal structure, and cortisol response dynamics of acute stress responses such that more severe lifetime stress is associated with smaller amygdalar and hippocampal volumes and flatter cortisol reactivity and recovery patterns to acute laboratory stress.\

### Presentations

1.  **Higgins, E. T.** (2025, May). *Brain-Immune Relationships in Asthma*. Presented at the UW-Madison Clinical Psychology departmental weekly lunch and learn proseminar.

    Slides available [here](https://github.com/higgins5/Portfolio/blob/main/documents/presentations/Higgins_capstone_final.pdf)

2.  **Higgins, E. T.**, Busse, W. W., Esnault, S., Klaus, D. R., Frye, C. J., & Rosenkranz, M. A. (2024, June). *Brain and cortisol responses to psychosocial stress are associated with provoked airway inflammation in Th17-related pathways in asthma.* Presentated at the 2024 Psychoneuroimmunology Research Society Annual Meeting, Halifax, Nova Scotia, Canada.

    **Abstract:** Individuals with asthma, a widespread chronic inflammatory disease of the airways, suffer increased prevalence and impact of stress, depression, and anxiety. Emotion-related neurocircuitry, activated by psychological stress, may intensify airway inflammatory responses. However, little is known about the neural mechanisms and descending pathways important in the context of acute stress and allergen exposure. In a within-subjects design with 28 adults with asthma, we measured brain glucose metabolism during the Trier Social Stress Test (TSST) and a non-stressful control task using \[18F\]fluorodeoxyglucose positron emission tomography (PET). Salivary cortisol was collected during the stress/control task and PET scan, to quantify physiological stress responses. Airway inflammation was measured using fraction of exhaled nitric oxide (FeNO), sputum % eosinophils, and expression of mRNA from cytokines produced by Th17 cells, before and 24hr after airway provocation with whole-lung allergen challenge (WL-AG). Acute stress significantly increased salivary cortisol (stats), but did not significantly increase airway inflammation overall. Following stress, salivary cortisol was correlated with IL-23A mRNA expression (t(22.1) = 2.38, p = 0.026) and FeNO (t(21.5) = 2.17, p = 0.041). In the brain, acute psychosocial stress was associated with increased glucose metabolism in the cerebellum and decreased motor cortex activity, relative to the control condition. Salivary cortisol was positively correlated with glucose metabolism in regions including the salience network. Importantly, acute stress-evoked salience network glucose metabolism predicted increased IL-23A mRNA expression following WL-AG. Results advance our understanding of the efferent arm of the lung-brain axis in humans. Although acute stress did not significantly increase airway inflammation in the whole group, results indicate that individual differences in brain and cortisol responses to acute psychosocial stress are associated with provoked airway inflammation in Th17-related pathways. This work motivates the need to tailor asthma interventions to individual variation in pulmonary and extrapulmonary processes in airway diseases.

    Slides available [here](https://github.com/higgins5/Portfolio/blob/main/documents/presentations/Higgins_PNIRS2024_presentation.pdf)

3.  **Higgins, E. T.** (2023, November). *Challenging the Brain & Lungs: Impacts of acute stress on the brain, cortisol, and inflammatory responses in asthma*. Presented at the 38th Annual First Year Project Symposium Madison, WI.

    **Abstract:** Individuals with asthma, a common chronic inflammatory disease of the airways, suffer increased prevalence and impact of stress, depression, and anxiety. Emotion-related neurocircuitry, activated by psychological stress, may intensify airway inflammatory responses. However, little is known about the neural mechanisms and descending pathways important in the context of acute stress and allergen exposure. In 28 adults with asthma, we measured brain glucose metabolism during the Trier Social Stress Test (TSST) and a non-stressful control test using \[18F\]fluorodeoxyglucose positron emission tomography (PET), with a within-subjects design. Salivary cortisol was collected during the stress/control test and PET scan, to quantify physiological stress responses. Airway inflammation was measured using fraction of exhaled nitric oxide (FeNO), sputum % eosinophils, and Th17 mRNA transcript expression before and 24hr after airway provocation with whole-lung allergen challenge (WL-AG). Acute psychosocial stress was associated with increased glucose metabolism in the cerebellum and decreased motor cortex activity, relative to the control condition. Significantly increased cortisol during stress was positively correlated with glucose metabolism in regions including those in the salience network, and correlated with IL-23A mRNA expression (t(22.1) = 2.38, p = .026) and FeNO (t(21.5) = 2.17, p = .041) following stress. Importantly, stress-evoked amygdala and dorsal anterior cingulate cortex activity predicted increased IL-23A mRNA expression following WL-AG. Contrary to hypotheses, however, acute stress did not significantly increase airway inflammation. This project advances the understanding of the efferent arm of the lung-brain axis in humans. Results indicate that individual differences in brain and cortisol responses to acute psychosocial stress are associated with provoked airway inflammation in the Th17 pathway. This work moves us closer to tailoring asthma prevention and treatment to individual differences in both pulmonary and extrapulmonary processes in airway diseases.

    Slides available [here](https://github.com/higgins5/Portfolio/blob/main/documents/presentations/Higgins_FYP_final.pdf)

4.  **Higgins, E. T.**, ... (2023, October 30). *Challenging the Brain & Lungs: Impacts of acute stress on the brain, cortisol, and inflammatory responses in asthma*. Presented at the UW-Madison Clinical Psychology departmental weekly lunch and learn proseminar.

    **Abstract:** Individuals with asthma, a common chronic inflammatory disease of the airways, suffer increased prevalence and impact of stress, depression, and anxiety. Emotion-related neurocircuitry, activated by psychological stress, may intensify airway inflammatory responses. However, little is known about the neural mechanisms and descending pathways important in the context of acute stress and allergen exposure. In 28 adults with asthma, we measured brain glucose metabolism during the Trier Social Stress Test (TSST) and a non-stressful control test using \[18F\]fluorodeoxyglucose positron emission tomography (PET), with a within-subjects design. Salivary cortisol was collected during the stress/control test and PET scan, to quantify physiological stress responses. Airway inflammation was measured using fraction of exhaled nitric oxide (FeNO), sputum % eosinophils, and Th17 mRNA transcript expression before and 24hr after airway provocation with whole-lung allergen challenge (WL-AG). Acute psychosocial stress was associated with increased glucose metabolism in the cerebellum and decreased motor cortex activity, relative to the control condition. Significantly increased cortisol during stress was positively correlated with glucose metabolism in regions including those in the salience network, and correlated with IL-23A mRNA expression (t(22.1) = 2.38, p = .026) and FeNO (t(21.5) = 2.17, p = .041) following stress. Importantly, stress-evoked amygdala and dorsal anterior cingulate cortex activity predicted increased IL-23A mRNA expression following WL-AG. Contrary to hypotheses, however, acute stress did not significantly increase airway inflammation. This project advances the understanding of the efferent arm of the lung-brain axis in humans. Results indicate that individual differences in brain and cortisol responses to acute psychosocial stress are associated with provoked airway inflammation in the Th17 pathway. This work moves us closer to tailoring asthma prevention and treatment to individual differences in both pulmonary and extrapulmonary processes in airway diseases.

    Slides available [here](https://github.com/higgins5/Portfolio/blob/main/documents/presentations/Higgins_clinical_prosem_2023.pdf)

5.  **Higgins, E. T.**, Busse, W. W., Esnault, S., Klaus, D. R., & Rosenkranz, M. A. (2023, June). *Chronic Stress Moderates Effects of Acute Stress on Allergen-Induced Asthmatic Inflammation.* Presented virtually at the 2023 Plasticity of Well-being Summer Workshop, Madison, WI.

    **Abstract:** Neurocircuitry recruited by psychological stress may magnify asthmatic airway inflammation, but little is known about the neural and molecular mechanisms. During the Trier Social Stress Test (TSST), we measured brain glucose metabolism (FDG-PET) and salivary cortisol. Airway inflammation was measured before and 24hr after airway allergen challenge (AG). Higher chronic stress predicted less increase in sputum eosinophils but greater increase in IL-17 mRNA expression following TSST and AG. Increased cortisol during the TSST correlated with greater salience network activation, which also predicted greater IL-23A and less CCL2 mRNA expression. Overall, chronic stress moderated acute stress’ effects on AG-induced airway inflammation, and TSST-related neural activity predicted IL-17 pathway signaling. Results offer insight into brain-to-lung signaling following acute stress, superimposed on varying levels of chronic stress, which may impact which inflammatory pathways AG exposure engages.

    Slides available [here](https://github.com/higgins5/Portfolio/blob/main/documents/presentations/Higgins_PWB_u24workshop.pdf)

6.  **Higgins, E. T.**, Busse, W. W., Esnault, S., Klaus, D., & Rosenkranz, M. A. (2023, February). *Stress neurocircuitry and airway inflammation in asthma.* Presented at the Psychoneuroimmunology Research Society Virtual Trainee Event.

    **Abstract:** Asthma is a highly prevalent airway disease marked by episodic and recurrent respiratory symptoms and increased prevalence and impact of stress, depression, and anxiety. Psychological stress intensifies airway inflammatory responses, likely contributing to individual differences in asthma pathobiology and incomplete symptom management. Given the role of Th17-associated pathways in both airway inflammation and psychological distress, they may link emotion-related neurocircuitry and asthmatic inflammation. However, the neural mechanisms and descending pathways by which psychological stress impacts asthmatic inflammation are largely unknown. To assess the effects of acute stress on neurocircuitry, we measured brain glucose metabolism during the Trier Social Stress Test (TSST) using \[F-18\]fluorodeoxyglucose positron emission tractography. Salivary cortisol was collected to quantify physiological stress responses. Airway inflammatory measurements were acquired before and 24hr after airway provocation with whole-lung allergen challenge (WL-AG). Salivary cortisol area under the curve (AUC) was significantly greater during the TSST, relative to control condition (t(50) = -2.8, p = .007). Cortisol also showed a quadratic trend over time during the TSST, relative to control condition (t(319) = -4.15, p \< .001). Stress-evoked cortisol AUC was positively correlated with glucose metabolism in the bilateral insulae, anterior cingulate cortex (ACC), R amygdala, and cerebellum. Importantly, stress-evoked neural activity in bilateral amygdalae predicted increased expression of IL-23A mRNA in sputum following WL-AG. Results confirm that a greater physiological response to stress is associated with increased neural activity in stress- and emotion-responsive regions. Moreover, correlations between stress-evoked bilateral amygdalae activation and subsequent increased IL-23A mRNA expression following allergen challenge support our hypothesis that stress-related neurocircuitry predicts enhanced inflammatory signaling capacity. These results provide insight into potential brain-to-lung signaling pathways in response to psychosocial stress, which may ultimately suggest novel targets for asthma management.

    Slides available [here](https://github.com/higgins5/Portfolio/blob/main/documents/presentations/Higgins_PNIRStrainee_presentation2023.pdf)\
    Program available [here](https://github.com/higgins5/Portfolio/blob/main/documents/workshops/PNIRS_TraineeEventProgram.pdf)

7.  **Higgins, E. T.**, Davidson, R. J., & Rosenkranz, M. A. (2022, September). *Brain functional changes associated with mindfulness training in asthma.* Presentation at the Autumn School Mini Congress, Castle Rauischholzhausen, Ebsdorfergrund, Germany.

    **Abstract:** Psychological distress can negatively impact asthma control, airway inflammation, and treatment efficacy. Interventions that target emotion reactivity and regulation, such as Mindfulness-Based Stress Reduction (MBSR), have shown benefit in improving asthma control. Brain networks involved in emotion-processing have been linked to both mindfulness practice and asthma-related immune modulation; however, whether regions within these networks mediate MBSR’s impact on disease-related outcomes is unknown. Adults with asthma were randomized to an 8-week MBSR training (n = 35) or wait-list control group (n = 34). At baseline, post-intervention, and 4months post-intervention, we collected clinically-relevant asthma and psychological outcomes, and functional magnetic resonance imaging in response to emotionally-salient cues. Mindfulness training decreased amygdala and lateral prefrontal cortex responses to emotionally-salient cues relative to wait-list controls, which was correlated with MBSR-related increases in mindfulness. Additionally, increased anterior cingulate cortex response was associated with MBSR-related asthma control improvements and decreased depressive symptoms, but also with decreased mindfulness and increased distress over time. For both groups, reduced insula responses to emotionally-salient cues correlated with decreased distress and inflammation. In asthmatic adults, MBSR training changed neural responses to emotionally-salient cues, which was associated with increased mindfulness and asthma control. This suggests that mindfulness training alters the reactivity and regulation of neural responses to emotionally-salient cues, which predicts symptom improvements. In all participants, decreased neural responses in emotion-relevant regions correlated with reduced distress and inflammation, advancing understandings of the complex neural mechanisms linking emotion and asthma. Overall, our results highlight the importance of targeting mind-body relationships in asthma treatment.

    Slides available [here](https://github.com/higgins5/Portfolio/blob/main/documents/presentations/Higgins_EPN2022_presentation.pdf)

### Workshops and Trainings Attended

1.  Name: Adult Mental Health First Aid Training\
    Organization: National Council for Mental Wellbeing\
    Date: March 2025\
    Description: Mental Health First Aid is a public educational program for early intervention. This course consisted of 2 hours of online content and 5.5 hours of in-person, instructor-led training focusing on learning to recognize the signs and symptoms of mental health challenges and/or crises. The workshop taught skills of listening nonjudgmentally, offering reassurance to someone who may be struggling, and directing individuals to professional support resources.\
    Modules available [here](https://github.com/higgins5/Portfolio/blob/main/documents/workshops/MHFA_modules.pdf)\
    
2.  Name: Mindfulness Mechanisms & Methods Meeting Small-Group Workshop\
    Organization: Washington University in St. Louis\
    Date: October 2023\
    Description: Following the public-facing Mindfulness Mechanisms & Methods Meeting, a selected group of promising trainees, junior investigators, and meeting speakers were invited to a two-day small-group workshop. This workshop included informal, intensive, and extended discussions; break-out groups; and active mindfulness practice. Discussions explored key challenges and future directions in mindfulness science research.\  
    Meeting program available [here](https://github.com/higgins5/Portfolio/blob/main/documents/workshops/M4_program_booklet_2023)\
    

3.  Name: 2023 Functional Magnetic Resonance Imaging of the Brain (FMRIB) Software Library (FSL) Course\
    Organization: FMRIB Analysis Group, Oxford University, UK\
    Date: September 2023\
    Description: This course was a 2-week virtual training that consisted of daily 3-hour tutorials and practicals, in addition to daily 2-hour recorded lectures completed before the tutorial/practical session. The course covered the theory and practice of basic and advanced functional, structural, diffusion, and resting-state neuroimaging analysis. Tutorials and practicals were taught by experts in the field.\
    Materials available [here](https://github.com/higgins5/Portfolio/blob/main/documents/workshops/FSL_Course_Material.pdf)\
    Certificate available [here](https://github.com/higgins5/Portfolio/blob/main/documents/workshops/FSL_Course_Certificate.pdf)

4.  Name: The Lung-Brain Axis in Health & Disease\
    Organization: European Psychoneuroimmunology Network, German-Endocrine-Brain-Immune-Network, and the Center for Mind, Brain, and Behavior\
    Date: September 2022\
    Description: This Autumn School Series in Ebsdorfergrund, Germany focused on neuroscience, immunology, and mental health/stress research at the nexus of the brain and lungs. The intensive week-long training consisted of daily lectures from the field's leaders (9am-3pm), group discussions, and hands-on workshops (3-6pm). This was an extraordinary chance to connect with fellow trainees and senior researchers, explore multidisciplinary research methods from basic to clinical, and discuss novel research approaches and interventions. Trainees also presented posters and short oral presentations.\
    Schedule available [here](https://github.com/higgins5/Portfolio/blob/main/documents/workshops/Lung_brain_axis_workshop_schedule.pdf)\
    Additional information [here](https://www.uni-giessen.de/de/fbz/zentren/ggl/events/autumnschool)

### Posters

1.  **Higgins, E. T.**, Busse, W. W., & Rosenkranz, M. A. (2025). Functional cerebellar subnuclei are associated with stress-related responses to acute psychosocial stress in asthma. Poster to be presentated at the Psychoneuroimunnology Research Society Annual Meeting: June, 2025; Bordeaux, France.\
    Poster available [here]()

2.  **Higgins, E. T.**, Recchio, J., Nord, E., Barnes, A., Gresham, L., Rosenkranz, M. A., Davidson, R. J., Slavich, G. M., & Schaefer, S. M. (2025). Inflammation and lifetime stressor severity are associated with blunted cortisol but not skin conductance responses to acute psychosocial stress. Citation poster presentation at the Society for Biopsychosocial Science and Medicine Annual Meeting; March, 2025; Seattle, WA\
    Poster available [here](https://github.com/higgins5/Portfolio/blob/main/documents/posters/Higgins_SBSM2025_poster.png)

3.  Haeffner, C. E., **Higgins, E. T.**, Laubacher, C. M., Gresham, L. K., Barnes, A. L., Skinner, S. E., Abercrombie, H. C., Rosenkranz, M. A., Davidson, R. J., Slavich, G. M., Schaefer, S. M. Associations between lifetime stressor severity, amygdala and hippocampal volumes, and cortisol responses to acute stress. Poster presentation at the Society for Affective Science Conference; March, 2025; Portland, OR.

4.  Morris, J., Poster, C., **Higgins, E. T.**, Sankaran, K., Mroczek, D., Schaefer, S. M. (2025). The time course of negative emotion and associations with time spent on work. Poster presentation at the Society for Affective Science Conference; March, 2025; Portland, OR.

5.  **Higgins, E. T.**, Busse, W. W., Grupe, D. W., Davidson, R. J., Rosenkranz, M. A. Mindfulness-Based Stress Reduction alters neural responses associated with asthma outcomes. Poster presented at the Mindfulness Mechanisms & Methods Meeting. October, 2023; St. Louis, MS.\
    Poster available [here](https://github.com/higgins5/Portfolio/blob/main/documents/posters/Higgins_M42023_poster.pdf)

6.  **Higgins, E. T.**, Davidson, R. J., Busse, W. W., & Rosenkranz, M. A. Brain functional changes associated with mindfulness training-related improvement in asthma control. Featured poster presentation at American Academy of Asthma, Allergy, & Inflammation (AAAAI) Annual Meeting; February, 2022; Phoenix, AZ.\
    Poster available [here](https://github.com/higgins5/Portfolio/blob/main/documents/posters/AAAAI_poster_final.pdf)

## Clinical Experiences

### Practicum

**placeholder draft text**\
Description: Description: As a Research Assistant for an ongoing NIH-funded R01 study, I have over four semesters of experience administering cognitive assessments, including the Repeatable Battery for the Assessment of Neuropsychological Status (RBANS), the Mnemonic Similarity Task (MST), the Minnesota Card Sorting Test (MCST), and the Corsi block-tapping test. In this experience, I have gained a practical understanding of the nuance and care essential to effective, ethical participant interaction and data collection, particularly with vulnerable populations such as those with chronic inflammatory diseases like asthma. This set of cognitive tests is important for assessing cognitive function, particularly in aging or otherwise compromised populations. and I am certified in Mental Health First Aid, equipping me to compassionately and effectively support individuals experiencing psychological distress or crisis. I intend to continue running participants and administering these cognitive tests for the foreseeable future.\

```{r}
#| echo: false

practicum <- tibble::tibble(Participant = c("MI 3001", "MI 4011", "MI 4013", 
                               "MI 4015", "MI 4005", "MI 4017", 
                               "MI 4016", "MI 3003", "MI 4019", 
                               "MI 3006", "MI 4021", "MI 4023", 
                               "MI 3013", "MI 3015", "MI 4025",
                               "MI 4028", "MI 4031"),
               Date = c("6/14/24", "7/2/24", "7/18/24", "9/5/24", 
                        "9/10/24", "10/17/24", "10/24/24", "10/31/24", 
                        "11/21/24", "11/26/24", "12/12/24", "2/4/25", 
                        "3/7/25", "3/7/25", "3/25/25", "4/8/25", "5/20/25"),
               Semester = c("S24", "S24", "S24", 
                            "F24", "F24", "F24", "F24", "F24", "F24", "F24", "F24",
                            "Sp25", "Sp25", "Sp25", "Sp25", "Sp25", "Sp25"),
               `Assessment(s)` = rep("RBANS, MST, Corsi, MCST",17),
               `Duration (hours)` = c(0.75, 0.75, 0.75, 0.75, 0.75, 
                                    0.75, 0.75, 0.75, 0.75, 0.75, 
                                    0.75, 0.75, 0.75, 0.5, 0.75, 
                                    0.75, 0.75)) 

dplyr::bind_rows(practicum,
          (practicum |> dplyr::summarise(
            Participant = "Total",
            Date = "",
            Semester = "",
            `Assessment(s)` = "",
            `Duration (hours)` = sum(`Duration (hours)`)))) |> 
  knitr::kable(digits = 2)

```


## Diversity Experiences

Diversity Statement

## Teaching and Mentoring Experiences

**placeholder draft text**\
The role of a scientist extends beyond research to include providing mentorship and support to science learners, which is equally vital to advancing the field. Outside of coursework and lab responsibilities, I have strengthened my leadership, mentorship, and communication skills, with a focus on applied data science in human behavior. Data science methods are complex yet indispensable tools for scientists across disciplines, and similarly important for fostering science literacy among non-expert audiences. Throughout my graduate career, I have leveraged my statistics expertise through one-on-one and group mentorship, as well as in small-group advising and teaching settings.\ 

In the Rosenkranz Lab, I have led several statistical presentations and discussions, including on topics such as Piecewise Linear Mixed Models (presentation slides [here](https://github.com/higgins5/Portfolio/blob/main/documents/presentations/Higgins_PiecewiseLMEM.pdf)), Advanced Outlier Detection (slides [here](https://github.com/higgins5/Portfolio/blob/main/documents/presentations/Higgins_Cook'sD_EffectSizes.pdf)), and Multiple Imputation in Longitudinal/Mixed Model Analyses (slides [here](https://github.com/higgins5/Portfolio/blob/main/documents/presentations/Higgins_multipleimputation.pdf)). Additionally, I have provided statistical support and data visualizations for collaborators analyzing salivary cortisol data using multilevel modeling (example [here]( https://docs.google.com/document/d/1xASuuZPJLxRfzrwP_d3cOHdzkq5gO5HGzKA-N1SVnbY/edit?tab=t.0)). These opportunities have strengthened my ability to distill and communicate complex technical information into clear, accessible components for diverse audiences, while refining my skills in delivering presentations and facilitating discussions.\ 

Further highlighting my commitment to data science mentorship, I have served as a PhD mentor for students pursuing their Master of Science in Psychology: Data Science in Human Behavior for the past four semesters, beginning in Spring 2024. In this role, I guide groups of 2-4 students through developing theory-grounded, application-oriented questions and hypotheses, supporting both their semester projects and final Capstone projects. I also advise data management, statistical modeling, and interpretation for these projects, meeting with students at least once per week. See Faculty Chat video [here]( https://datascience.psych.wisc.edu/2025/02/17/faculty-chat-with-estelle-higgins/) for more details. We have partnered with Healthy Minds Innovations to analyze large-scale multidimensional data from the [Healthy Minds Program app]( https://hminnovations.org/meditation-app). This role has bolstered my leadership and mentoring competence, helped cultivate students’ critical thinking and science communication skills, and deepened my own experience in analyzing large datasets to answer questions aligned with my broader wellbeing research goals.\ 

In addition to mentoring master’s students, I have worked closely with several undergraduate students. Since Spring 2023 semester, I have provided basic and advanced statistical guidance, writing and poster feedback, and career support to an honors Neurobiology undergraduate senior at the time. Together, we are finalizing a co-first-author manuscript examining intersections between lifetime stressor exposure, amygdalar and hippocampal structure, and acute stress-related cortisol responses. Following her graduation, she joined the NIH Intramural Postbaccalaureate Program and will start her PhD at Yale University this Fall 2025.\ 

Since Fall 2023 semester, I have also mentored an undergraduate research assistant in the Rosenkranz Lab. With our guidance, she has completed several small independent projects spanning literature review, research proposal, and data analysis. She will also be assisting with cognitive testing data collection in an NIH-funded R01 study. As a 2025 Hilldale Fellow, her senior honors project in Psychology & Neurobiology will focus on the relationships among asthma, depression, and gut microbiota.\ 

Additionally, during Summer and Fall 2024 semesters, I offered substantial statistical support for another senior honors thesis in Psychology. This project used piecewise linear mixed effects models with nested random effects to assess relationships between facial electromyography responses to emotion-related stimuli, at-home daily diary reports, and time spent on paid and unpaid work. The student will continue his research training this summer at the McGill Neurological Institute with support from a Fulbright scholarship. I am committed to continuing my direct mentoring of undergraduate and graduate students, including the three current undergraduates in the Rosenkranz Lab, the current Data Science in Human Behavior graduate cohort, and future trainees.\

These mentorship experiences have not only been enriching learning opportunities for me to strengthen my technical and interpersonal skills, but they have also reaffirmed the importance of helping students identify and cultivate their potential—evidenced in their outstanding achievements in diverse areas/directions. It is vital to me that the scope of my mentorship is holistic, encompassing not just statistical and research advising, but also career, professional, and personal guidance, as appropriate. Overall, I am passionate about leveraging accessible and rigorous data science as a tool for increasing engagement with science, promoting equity in scientific training, and fostering broad-reaching scientific literacy. I am eager to continue this work as an integral part of my academic and professional path.\
